# -*- coding: utf-8 -*-
"""RAG simple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SnxdR1zVQj60bisLczb2PXl3j-1SJoeK
"""

# Commented out IPython magic to ensure Python compatibility.
# Install the required LangChain, Gemini, and Chroma packages
# %pip install -U langchain-community langchain-chroma langchain-google-genai chromadb

# Configure the Gemini API key securely for the notebook

import os
from getpass import getpass

GOOGLE_API_KEY = getpass("Enter your Gemini API key: ")

os.environ["GOOGLE_API_KEY"] = GOOGLE_API_KEY

print("Gemini API key configured successfully!")

# Import the webpage loader and HTML filter for extracting the main article
from langchain_community.document_loaders import WebBaseLoader
from bs4 import SoupStrainer

# Load only the main content of the AWS RAG webpage
loader = WebBaseLoader(
    web_path=[
        "https://aws.amazon.com/what-is/retrieval-augmented-generation/"
    ],
    bs_kwargs={
        "parse_only": SoupStrainer("main")
    }
)

clean_docs = loader.load()

print("Clean documents loaded:", len(clean_docs))

## Import the recursive text splitter used to divide the webpage into smaller chunks
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Split the cleaned AWS article into overlapping chunks for embedding and retrieval
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1500,
    chunk_overlap=200
)

clean_splits = text_splitter.split_documents(clean_docs)

print("Number of clean chunks:", len(clean_splits))

# Check the first clean chunk to verify that the AWS article was loaded correctly
print(clean_splits[0].page_content[:1000])

# Import Gemini embeddings for converting document chunks into numerical vectors

from langchain_google_genai import GoogleGenerativeAIEmbeddings
# Initialize the Gemini embedding model used to create vectors for the document chunks

embeddings = GoogleGenerativeAIEmbeddings(
    model="gemini-embedding-001"
)

print("Gemini embeddings ready")

# Create a new Chroma vector store using the clean document chunks and Gemini embeddings
from langchain_chroma import Chroma

vectorstore_clean = Chroma.from_documents(
    documents=clean_splits,
    embedding=embeddings,
    collection_name="rag_clean"
)

print("Clean vector store created")

# Check how many document vectors were successfully stored in Chroma

 print("Number of vectors:", vectorstore_clean._collection.count())

# Create a retriever that searches Chroma for the four most relevant chunks

 retriever_clean = vectorstore_clean.as_retriever(
    search_kwargs={"k": 4}
)

print("Clean retriever created")

# Create Gemini 2.5 Flash-Lite as the language model for generating RAG answers

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash-lite",
    temperature=0
)

print("Gemini 2.5 Flash-Lite ready")

# Combine the retrieved document chunks into a single text context for the LLM

 def format_docs(docs):
    return "\n\n".join(
        doc.page_content
        for doc in docs
    )

# Import the LangChain prompt template used to create the RAG prompt

from langchain_core.prompts import ChatPromptTemplate
# Create a prompt that instructs Gemini to answer only from the retrieved context

prompt = ChatPromptTemplate.from_template("""
You are a helpful AI assistant.

Answer the user's question using ONLY the information provided in the context.

If the context contains the answer, explain it clearly and completely.

If the context does not contain the answer, say:
"I don't know based on the provided context."

Context:
{context}

Question:
{question}

Answer:
""")

from langchain_community.document_loaders import WebBaseLoader

loader = WebBaseLoader(
    web_path=[
        "https://aws.amazon.com/what-is/retrieval-augmented-generation/"
    ],
    bs_kwargs={
        "parse_only": SoupStrainer("main")
    }
)

clean_docs = loader.load()

print("Clean documents loaded:", len(clean_docs))

# Import the components needed to pass the question through the RAG chain and parse Gemini's response

from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

# Build the complete RAG chain by connecting the retriever, prompt, Gemini model, and output parser

rag_chain_clean = (
    {
        "context": retriever_clean | format_docs,
        "question": RunnablePassthrough()
    }
    | prompt
    | llm
    | StrOutputParser()
)

print("Clean RAG chain created")

#Questions
response = rag_chain_clean.invoke(
    "What is Retrieval-Augmented Generation?"
)

print(response)

# X Questions
response = rag_chain_clean.invoke(
    "What is cs"
)

print(response)

#Questions
response = rag_chain_clean.invoke(
    "What is the difference between RAG and semantic search?"
)

print(response)